const SHOW_LOADING = "SHOW_LOADING";
const ADD_TODO = "ADD_TODO";
const TOGGLE_COMPLETE = "TOGGLE_COMPLETE";
const DELETE_TODO = "DELETE_TODO";
const CHANGE_TYPE = "CHANGE_TYPE";
const SET_TODO_NAME = "SET_TODO_NAME";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const SHOW_ERROR = "SHOW_ERROR";
const SET_TODOS = "SET_TODO";

export {
    SHOW_LOADING,
    ADD_TODO,
    TOGGLE_COMPLETE,
    DELETE_TODO,
    CHANGE_TYPE,
    SET_TODO_NAME,
    LOGIN,
    LOGOUT,
    SHOW_ERROR,
    SET_TODOS,
};
